gt_path: "results/exp010/0/data/smooth"
latent_path: "results/pose_finetuning_020/pose"
pti:
    expressive_path: "results/exp010/0/expressive"
    ss_path: "results/exp010/0/ss_space_pose_020"
    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0
epochs: 100
batchsize: 1
lr: 0.0003
resolution: 512
