gt_path: "/data1/chenlong/online_model_set/face/lady9_s4_20240118/face"
latent_path: "results/lady9/ss/"
pti:
    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0
epochs: 100
batchsize: 8
lr: 0.0003
resolution: 512
