gt_path: "/data1/chenlong/0517/video/0522/2/results/man3_chenl_0521/data/smooth"
latent_path: "results/man3/ss_space_only_pose"
pti:
    expressive_path: "results/man3/expressive"
    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0
            - 
              alias: l2_mask
              name: L2Loss
              weights: 10.0
            - 
              alias: lpips_mask
              name: LPIPS
              weights: 10.0
epochs: 100
batchsize: 1
lr: 0.0003
resolution: 512
