gt_path: "results/exp010/0/data/smooth"
latent_path: "results/exp010/0/finetuned_ss_space_016"
pti:
    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 0.0
            - 
              alias: lpips
              name: LPIPS
              weights: 0.0
            - 
              alias: l2_mask
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips_mask
              name: LPIPS
              weights: 1.0
epochs: 100
batchsize: 1
lr: 0.0003
