gt_path: "results/exp010/0/data/smooth"
latent_path: "results/exp010/0/finetuned_ss_space"
pti:
    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0
epochs: 300
resolution: 512
