gt_path: "/data1/chenlong/0517/video/0522/kanghui_0/results/man3_chenl_0521/data/smooth"
latent_path: "/data1/chenlong/0517/video/0522/kanghui_0/results/man3_chenl_0521/data/style_space"
pti:
    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0
epochs: 100
batchsize: 4
lr: 0.001
