image_path: "images/wang.jpg"
latent_path: "./results/exp006/expressive"
cache_path: "./results/exp006/cache.pt"
video_image_path: "./results/exp006/data/smooth"
pti:

    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0

