gt_path: "/data1/chenlong/online_model_set/video/S1YRnPRL/video/smooth"
latent_path: "/data1/chenlong/0517/video/0822/YRKL6NhF/YRKL6NhF_exp_set_v4_depoly/exp/facial"
pti:
    net:
        base_filter_num: 64
        source_size: 64
        target_size: 4
        target_filter_num: 512

    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0
epochs: 50
batchsize: 8
lr: 0.0003
resolution: 512
