image_path: "puppet/woman/0.jpg"
latent_path: "./results/exp007/expressive"
cache_path: "./results/exp007/cache.pt"
video_image_path: "./results/exp007/data/smooth"
pti:

    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0

