gt_path: "results/exp010/0/data/smooth"
latent_path: "results/exp010/0/ss_space_only_pose"
pti:
    expressive_path: "results/exp010/0/expressive"
    losses:
            - 
              alias: l2_mask
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips_mask
              name: LPIPS
              weights: 1.0
epochs: 100
batchsize: 1
lr: 0.0003
resolution: 512
