gt_path: "results/exp010/0/data/smooth"
latent_path: "/data1/chenlong/0517/video/0813/kanghui_0/kanghui_0_exp_set_v3_depoly/exp/facial/"
pti:
    net:
        base_filter_num: 64
        source_size: 64
        target_size: 4
        target_filter_num: 512

    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1
            - 
              alias: lpips
              name: LPIPS
              weights: 1
            - 
              alias: l2_code
              name: L2Loss
              weights: 10
epochs: 100
batchsize: 8
lr: 0.003
resolution: 512
