gt_path: "results/kanghui/data/smooth"
latent_path: "results/kanghui/ss"
pti:
    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1.0
            - 
              alias: lpips
              name: LPIPS
              weights: 1.0
epochs: 100
batchsize: 1
lr: 0.0003
resolution: 512
