gt_path: "/data1/chenlong/online_model_set/video/S1YRnPRL/video/smooth"
latent_path: "/data1/chenlong/0517/video/0822/S1YRnPRL/S1YRnPRL_exp_set_v4_depoly/exp/facial"
pti:
    net:
        base_filter_num: 64
        source_size: 64
        target_size: 4
        target_filter_num: 512

    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1
            - 
              alias: lpips
              name: LPIPS
              weights: 1
            - 
              alias: l2_code
              name: L2Loss
              weights: 10
epochs: 10
batchsize: 8
lr: 0.003
resolution: 512
